### ISSUE TITLE
Cheating the game is very easy

### ISSUE THREAD

**Issue by Juraci** [samiheikki/javascript-guessing-game#148]
You just have to watch for the logo image to be downloaded for the current question for example: `UHlKUw==.png`

and in the console just execute

`atob('UHlKUw==');`

which results in: "PyJS"

**Comment by ghost** [comment]
I think that one possible solution is to change the "rename-images" gulp task:
Instead of renaming the images using base64, it can rename each image with different random string, and this string will be stored on each corresponding logo in logos.json. (let's say for example it will be "**randomId**" property)

Then in JsLogo.vue instead of **'../static/logos/' + window.btoa(this.logo) + '.png'**, it will be **'../static/logos/' +this.logo.randomId + '.png'**

Please let me know if you think it will work, and if so, if you would like to create a PR for it.

**Comment by samiheikki** [comment]
Fixed in #184
