### ISSUE TITLE
Tool logo should not contain tool name

### ISSUE THREAD

**Issue by Grawl** [samiheikki/javascript-guessing-game#26]
It's too easy to guess right answer if I see same word in image and answer button.

<img width="472" alt="2016-10-31 15 04 27" src="https://cloud.githubusercontent.com/assets/846774/19844732/725be990-9f7b-11e6-9dd3-5c3246ba5262.png">

**Comment by Grawl** [comment]
Not all tools have logo images that not contains tool name. Sometimes logo is a word written in unique font or lettering, like Coca-Cola. If so, we can overlap those logos with other image. Question mark in a circle, for example.

<img width="472" alt="2016-10-31 15 04 27" src="https://cloud.githubusercontent.com/assets/846774/19844797/2cf39d84-9f7c-11e6-92e0-f9470d22eba9.png">

**Comment by hzlmn** [comment]
@Grawl Even in this case not very hard to guess word, as only one starts with `S`. My proposal is to blur image and basically a little bit change algorithm for generating test answers.

**Comment by samiheikki** [comment]
I'd would add -1 to this proposition. App doesn't include well known brands like Coca-Cola that ppl can identify even tough part of the logo is hidden. Purpose of this game is to help memorize the logo/name combinations so that in situations like job interviews they seem more professional thanks for "knowing" about framework X.

Some of the questions are easy, like stapes.js, but there are over 100 questions so I don't see it as a bad thing that some of them are easy.

**Comment by Grawl** [comment]
@samiheikki if I can read one word into two places I cannot say I “know” what it means. I just see “stapes.js” and click a button with same word.
